### ISSUE TITLE
no such option: --no-follow-import-to

### ISSUE THREAD

**Issue by SwakinX** [Nuitka-Commander/nuitka-commander.github.io#94]
no such option: --no-follow-import-to
正确的应该是--nofollow-import-to.
还有我这2.4.5必需用这种格式来运行
Usage: python.exe -m nuitka [--module] [--run] [options] main_module.py
主程序不在最后或者加上双引号都是不行的，是版本原因吗，我没用过老版本的

**Comment by erduotong** [comment]
第一个问题这周末处理

**Comment by erduotong** [comment]
有终端环境吗？

**Comment by erduotong** [comment]
是否忘记添加`--main`
例如，应该`--main="main_module"`，这样作为一个参数，可以放在任何地方

**Comment by erduotong** [comment]
已修复

**Comment by SwakinX** [comment]
https://github.com/Nuitka-Commander/nuitka-commander.github.io/issues/94#issuecomment-2349221604
我试了下，是因为我加了--nofollow-import-to这个选项，mian.py必须放在后面，建议默认把--main=放最后面

**Comment by erduotong** [comment]
看看完整指令，我测试一下

**Comment by SwakinX** [comment]
python -m nuitka --standalone --python-flag="-S"  --include-package="certifi,charset_normalizer,idna,past,requests,urllib3,xml,http,six" --follow-imports --follow-stdlib --nofollow-import-to="PIL,yaml,airtest,scipy,pywinauto,doctest,bcrypt,certifi,distutils,future,lib2to3,chardet,cryptography"   --main="E:\Github\Release\MoonCancer-clear\MoonCancer.py"  --remove-output --output-dir="E:\Github\Release\build" --mingw64 --show-memory  --windows-uac-admin
这是能正常运行的，放到前面就会报错
